version: "3.8"

networks:
  localNetwork:
   name: scala-zio-example-local

services:
  # Note: If for some reason you are running the server in the container, 
  # don't forget to run `docker-compose build backend` before each run
  # to make sure that the image is up to date.
  backend:
    build:
      context: .
    networks:
      - localNetwork
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: 'jdbc:mysql://mysql:3306/localDatabase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
      MYSQL_USER: 'localUser'
      MYSQL_PASSWORD: 'localPassword'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 8080
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/api/v1/check/health" ]
      interval: 1s
      start_period: 5s
      retries: 500
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    networks:
      - localNetwork
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'localDatabase'
      MYSQL_USER: 'localUser'
      MYSQL_PASSWORD: 'localPassword'

      # Note: mySQL won't run without root password being set.
      # Though there are other root password options, the `MYSQL_ROOT_PASSWORD` is the most explicit.
      MYSQL_ROOT_PASSWORD: 'localPassword'

    healthcheck:
      test: mysql -h localhost -P 3306 --protocol=tcp -u $$MYSQL_USER --password=$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'SELECT 1'
      interval: 3s
      retries: 500
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
