
name: scala-zio-example CI

on:
  push:
    branches: 
      - main
  pull_request: 
    types: 
      - opened
      # "synchronize" means new commits pushed to the HEAD of the pull request branch
      - synchronize

permissions: read-all

jobs:
  cancel-previous:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: setup-scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: amazon-corretto@1.11

    - name: Compile, check formatting, lint, and run tests
      run: sbt compile styleCheck test
